/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2017-11-16 05:02:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>로그인 화면</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/admin.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("<!--\n");
      out.write("\tfunction fncLogin() {\n");
      out.write("\t\tvar id=document.loginForm.userId.value;\n");
      out.write("\t\tvar pw=document.loginForm.password.value;\n");
      out.write("\t\tif(id == null || id.length <1) {\n");
      out.write("\t\t\talert('ID 를 입력하지 않으셨습니다.');\n");
      out.write("\t\t\tdocument.loginForm.userId.focus();\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tif(pw == null || pw.length <1) {\n");
      out.write("\t\t\talert('패스워드를 입력하지 않으셨습니다.');\n");
      out.write("\t\t\tdocument.loginForm.password.focus();\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\t    document.loginForm.submit();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t//Call Back Method 이용 onload 시 Event 처리\n");
      out.write("\twindow.onload = function(){\n");
      out.write("\t\tdocument.loginForm.userId.focus();\n");
      out.write("\t\tdocument.getElementById(\"userId\").focus();\n");
      out.write("\t}\n");
      out.write("-->\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body bgcolor=\"#ffffff\" text=\"#000000\" >\n");
      out.write("\n");
      out.write("<form name=\"loginForm\"  method=\"post\" action=\"/login.do\" target=\"_parent\">\n");
      out.write("\n");
      out.write("<div align=\"center\">\n");
      out.write("\n");
      out.write("<TABLE WITH=\"100%\" HEIGHT=\"100%\" BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"0\">\n");
      out.write("<TR>\n");
      out.write("<TD ALIGN=\"CENTER\" VALIGN=\"MIDDLE\">\n");
      out.write("\n");
      out.write("<table width=\"650\" height=\"390\" border=\"5\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#D6CDB7\">\n");
      out.write("  <tr> \n");
      out.write("    <td width=\"10\" height=\"5\" align=\"left\" valign=\"top\" bordercolor=\"#D6CDB7\">\n");
      out.write("    \t<table width=\"650\" height=\"390\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("        <tr>\n");
      out.write("          <td width=\"305\">\n");
      out.write("            <img src=\"/images/logo-spring.png\" width=\"305\" height=\"390\"/>\n");
      out.write("          </td>\n");
      out.write("          <td width=\"345\" align=\"left\" valign=\"top\" background=\"/images/login02.gif\">\n");
      out.write("          \t<table width=\"100%\" height=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("              <tr> \n");
      out.write("                <td width=\"30\" height=\"100\">&nbsp;</td>\n");
      out.write("                <td width=\"100\" height=\"100\">&nbsp;</td>\n");
      out.write("                <td height=\"100\">&nbsp;</td>\n");
      out.write("                <td width=\"20\" height=\"100\">&nbsp;</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr> \n");
      out.write("                <td width=\"30\" height=\"50\">&nbsp;</td>\n");
      out.write("                <td width=\"100\" height=\"50\">\n");
      out.write("                \t<img src=\"/images/text_login.gif\" width=\"91\" height=\"32\"/>\n");
      out.write("                </td>\n");
      out.write("                <td height=\"50\">&nbsp;</td>\n");
      out.write("                <td width=\"20\" height=\"50\">&nbsp;</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr> \n");
      out.write("                <td width=\"200\" height=\"50\" colspan=\"4\"></td>\n");
      out.write("              </tr>              \n");
      out.write("              <tr> \n");
      out.write("                <td width=\"30\" height=\"30\">&nbsp;</td>\n");
      out.write("                <td width=\"100\" height=\"30\">\n");
      out.write("                \t<img src=\"/images/text_id.gif\" width=\"100\" height=\"30\"/>\n");
      out.write("                </td>\n");
      out.write("                <td height=\"30\">\n");
      out.write("                  <input type=\"text\" name=\"userId\"  class=\"ct_input_g\" \n");
      out.write("                  \t\t\t\tstyle=\"width:180px; height:19px\"  maxLength='50'\n");
      out.write("                  \t\t\t\tonKeydown=\"javascript:if(event.keyCode == 13) fncLogin();\"/>\n");
      out.write("          \t\t</td>\n");
      out.write("                <td width=\"20\" height=\"30\">&nbsp;</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr> \n");
      out.write("                <td width=\"30\" height=\"30\">&nbsp;</td>\n");
      out.write("                <td width=\"100\" height=\"30\">\n");
      out.write("                \t<img src=\"/images/text_pas.gif\" width=\"100\" height=\"30\"/>\n");
      out.write("                </td>\n");
      out.write("                <td height=\"30\">                    \n");
      out.write("                    <input type=\"password\" name=\"password\" class=\"ct_input_g\" \n");
      out.write("                   \t\t\t\tstyle=\"width:180px; height:19px\"  maxLength=\"50\" \n");
      out.write("                   \t\t\t\tonKeydown=\"javascript:if(event.keyCode == 13) fncLogin();\"/>\n");
      out.write("                </td>\n");
      out.write("                <td width=\"20\" height=\"30\">&nbsp;</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr> \n");
      out.write("              \n");
      out.write("                <td width=\"30\" height=\"20\">&nbsp;</td>\n");
      out.write("                <td width=\"100\" height=\"20\">&nbsp;</td>\n");
      out.write("                <td height=\"20\" align=\"center\">\n");
      out.write("   \t\t\t\t    <table width=\"136\" height=\"20\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                       <tr> \n");
      out.write("                         <td width=\"56\">\n");
      out.write("                         \t<a href=\"javascript:fncLogin();\">\n");
      out.write("                         \t\t<img src=\"/images/btn_login.gif\" width=\"56\" height=\"20\" border=\"0\"/>\n");
      out.write("                         \t</a>\n");
      out.write("                         </td>\n");
      out.write("                         <td width=\"10\">&nbsp;</td>\n");
      out.write("                         <td width=\"70\">\n");
      out.write("                         \t<a href=\"addUserView.jsp;\">\n");
      out.write("                         \t\t<img src=\"/images/btn_add.gif\" width=\"70\" height=\"20\" border=\"0\">\n");
      out.write("                         \t</a>\n");
      out.write("                         </td>\n");
      out.write("                       </tr>\n");
      out.write("                     </table>\n");
      out.write("                 </td>\n");
      out.write("                 <td width=\"20\" height=\"20\">&nbsp;</td>\n");
      out.write("                </tr>\n");
      out.write("              </table>\n");
      out.write("            </td>\n");
      out.write("      \t</tr>                            \n");
      out.write("      </table>\n");
      out.write("      </td>\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("</TD>\n");
      out.write("</TR>\n");
      out.write("</TABLE>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
