/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2017-12-04 07:50:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"EUC-KR\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>로그인 화면</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/css/admin.css\" type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- CDN(Content Delivery Network) 호스트 사용 -->\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t   \r\n");
      out.write("\t\t/*=============jQuery 변경 주석처리 =============\r\n");
      out.write("\t\tfunction fncLogin() {\r\n");
      out.write("\t\t\tvar id=document.loginForm.userId.value;\r\n");
      out.write("\t\t\tvar pw=document.loginForm.password.value;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(id == null || id.length <1) {\r\n");
      out.write("\t\t\t\talert('ID 를 입력하지 않으셨습니다.');\r\n");
      out.write("\t\t\t\tdocument.loginForm.userId.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pw == null || pw.length <1) {\r\n");
      out.write("\t\t\t\talert('패스워드를 입력하지 않으셨습니다.');\r\n");
      out.write("\t\t\t\tdocument.loginForm.password.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//Call Back Method 이용 onload 시 Event 처리\r\n");
      out.write("\t\twindow.onload = function(){\r\n");
      out.write("\t\t\tdocument.getElementById(\"userId\").focus();\r\n");
      out.write("\t\t}========================================\t*/\r\n");
      out.write("\t\t$( function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//==> DOM Object GET 3가지 방법 ==> 1. $(tagName) : 2.(#id) : 3.$(.className)\r\n");
      out.write("\t\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//==> 추가된부분 : \"Login\"  Event 연결\r\n");
      out.write("\t\t\t$(\"img[src='/images/btn_login.gif']\").on(\"click\" , function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar id=$(\"input:text\").val();\r\n");
      out.write("\t\t\t\tvar pw=$(\"input:password\").val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(id == null || id.length <1) {\r\n");
      out.write("\t\t\t\t\talert('ID 를 입력하지 않으셨습니다.');\r\n");
      out.write("\t\t\t\t\t$(\"input:text\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(pw == null || pw.length <1) {\r\n");
      out.write("\t\t\t\t\talert('패스워드를 입력하지 않으셨습니다.');\r\n");
      out.write("\t\t\t\t\t$(\"input:password\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//$(\"form\").attr(\"method\" , \"POST\");\r\n");
      out.write("\t\t\t\t//$(\"form\").attr(\"action\" , \"/login.do\");\r\n");
      out.write("\t\t\t\t//$(\"form\").attr(\"target\" , \"_parent\");\r\n");
      out.write("\t\t\t    //$(\"form\").submit();\r\n");
      out.write("\t\t\t\t//==> 위의 4실행문과 같은의미\t\t\t    \r\n");
      out.write("\t\t\t\t$(\"form\").attr(\"method\",\"POST\").attr(\"action\",\"/user/login\").attr(\"target\",\"_parent\").submit();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//*=============jQuery 추가된부부분 : 회원원가입화면이동 =============\r\n");
      out.write("\t\t$( function() {\r\n");
      out.write("\t\t\t//==> 추가된부분 : \"addUser\"  Event 연결\r\n");
      out.write("\t\t\t$(\"img[src='/images/btn_add.gif']\").on(\"click\" , function() {\r\n");
      out.write("\t\t\t\tself.location = \"/user/addUser\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\t\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#ffffff\" text=\"#000000\" >\r\n");
      out.write("\r\n");
      out.write("<!-- ////////////////// jQuery Event 처리로 변경됨 /////////////////////////\r\n");
      out.write(" <form name=\"loginForm\"  method=\"post\" action=\"/user/login\" target=\"_parent\">\r\n");
      out.write("////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("<form>\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\" >\r\n");
      out.write("\r\n");
      out.write("<TABLE WITH=\"100%\" HEIGHT=\"100%\" BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"0\">\r\n");
      out.write("<TR>\r\n");
      out.write("<TD ALIGN=\"CENTER\" VALIGN=\"MIDDLE\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"650\" height=\"390\" border=\"5\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#D6CDB7\">\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td width=\"10\" height=\"5\" align=\"left\" valign=\"top\" bordercolor=\"#D6CDB7\">\r\n");
      out.write("    \t<table width=\"650\" height=\"390\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"305\">\r\n");
      out.write("            <img src=\"/images/logo-spring.png\" width=\"305\" height=\"390\"/>\r\n");
      out.write("          </td>\r\n");
      out.write("          <td width=\"345\" align=\"left\" valign=\"top\" background=\"/images/login02.gif\">\r\n");
      out.write("          \t<table width=\"100%\" height=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"30\" height=\"100\">&nbsp;</td>\r\n");
      out.write("                <td width=\"100\" height=\"100\">&nbsp;</td>\r\n");
      out.write("                <td height=\"100\">&nbsp;</td>\r\n");
      out.write("                <td width=\"20\" height=\"100\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"30\" height=\"50\">&nbsp;</td>\r\n");
      out.write("                <td width=\"100\" height=\"50\">\r\n");
      out.write("                \t<img src=\"/images/text_login.gif\" width=\"91\" height=\"32\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td height=\"50\">&nbsp;</td>\r\n");
      out.write("                <td width=\"20\" height=\"50\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"200\" height=\"50\" colspan=\"4\"></td>\r\n");
      out.write("              </tr>              \r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"30\" height=\"30\">&nbsp;</td>\r\n");
      out.write("                <td width=\"100\" height=\"30\">\r\n");
      out.write("                \t<img src=\"/images/text_id.gif\" width=\"100\" height=\"30\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td height=\"30\">\r\n");
      out.write("                  <input \ttype=\"text\" name=\"userId\"  id=\"userId\"  class=\"ct_input_g\" \r\n");
      out.write("                  \t\t\t\tstyle=\"width:180px; height:19px\"  maxLength='50'/>          \r\n");
      out.write("          \t\t</td>\r\n");
      out.write("                <td width=\"20\" height=\"30\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"30\" height=\"30\">&nbsp;</td>\r\n");
      out.write("                <td width=\"100\" height=\"30\">\r\n");
      out.write("                \t<img src=\"/images/text_pas.gif\" width=\"100\" height=\"30\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td height=\"30\">                    \r\n");
      out.write("                    <input \ttype=\"password\" name=\"password\" class=\"ct_input_g\" \r\n");
      out.write("                    \t\t\t\tstyle=\"width:180px; height:19px\"  maxLength=\"50\" />\r\n");
      out.write("                </td>\r\n");
      out.write("                <td width=\"20\" height=\"30\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"30\" height=\"20\">&nbsp;</td>\r\n");
      out.write("                <td width=\"100\" height=\"20\">&nbsp;</td>\r\n");
      out.write("                <td height=\"20\" align=\"center\">\r\n");
      out.write("   \t\t\t\t    <table width=\"136\" height=\"20\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                       <tr> \r\n");
      out.write("                         <td width=\"56\">\r\n");
      out.write("                         \t<!-- ////////////////// jQuery Event 처리로 변경됨 /////////////////////////\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:fncLogin();\">\r\n");
      out.write("                         \t\t<img src=\"/images/btn_login.gif\" width=\"56\" height=\"20\" border=\"0\"/>\r\n");
      out.write("                         \t</a>\r\n");
      out.write("\t\t\t\t\t\t\t////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("                         \t\t<img src=\"/images/btn_login.gif\" width=\"56\" height=\"20\" border=\"0\"/>\r\n");
      out.write("                         </td>\r\n");
      out.write("                         <td width=\"10\">&nbsp;</td>\r\n");
      out.write("                         <td width=\"70\">\r\n");
      out.write("                         \t<!-- ////////////////// jQuery Event 처리로 변경됨 /////////////////////////\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/user/addUser\">\r\n");
      out.write("                         \t\t<img src=\"/images/btn_add.gif\" width=\"70\" height=\"20\" border=\"0\">\r\n");
      out.write("                         \t</a>\r\n");
      out.write("\t\t\t\t\t\t\t////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("                       \t\t\t<img src=\"/images/btn_add.gif\" width=\"70\" height=\"20\" border=\"0\">\r\n");
      out.write("                         </td>\r\n");
      out.write("                       </tr>\r\n");
      out.write("                     </table>\r\n");
      out.write("                 </td>\r\n");
      out.write("                 <td width=\"20\" height=\"20\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </table>\r\n");
      out.write("            </td>\r\n");
      out.write("      \t</tr>                            \r\n");
      out.write("      </table>\r\n");
      out.write("      </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</TD>\r\n");
      out.write("</TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
