/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2017-10-27 01:59:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model2.mvc.service.user.vo.*;

public final class readUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	UserVO vo=(UserVO)request.getAttribute("vo");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>회원정보조회</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/admin.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#ffffff\" text=\"#000000\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"37\" border=\"0\" cellpadding=\"0\"\tcellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"15\" height=\"37\">\r\n");
      out.write("\t\t\t<img src=\"/images/ct_ttl_img01.gif\" width=\"15\" height=\"37\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td background=\"/images/ct_ttl_img02.gif\" width=\"100%\" style=\"padding-left:10px;\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"93%\" class=\"ct_ttl01\">회원정보조회</td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\" align=\"right\">&nbsp;</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td width=\"12\" height=\"37\"><img src=\"/images/ct_ttl_img03.gif\" width=\"12\" height=\"37\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-top:13px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("\t\t\t아이디 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"105\">");
      out.print(vo.getUserId() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("\t\t\t이름 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print(vo.getUserName() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">주소</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print(vo.getAddr() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">휴대전화번호</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print(vo.getPhone() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">이메일 </td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">\r\n");
      out.write("\t\t\t<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td height=\"26\">");
      out.print(vo.getEmail() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">가입일자</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print(vo.getRegDate() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\tstyle=\"margin-top:10px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"53%\"></td>\r\n");
      out.write("\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"17\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\" style=\"padding-top:3px;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/updateUserView.do?userId=");
      out.print(vo.getUserId() );
      out.write("\">수정</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"30\"></td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td width=\"17\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\" style=\"padding-top:3px;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:history.go(-1);\">확인</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
