/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2017-11-02 02:50:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model2.mvc.service.domain.User;
import com.model2.mvc.service.domain.Product;

public final class getProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

	Product product = (Product)request.getAttribute("product");
	User user = (User)session.getAttribute("user");
	String menu = (String)request.getParameter("menu");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/admin.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<title>상품상세조회</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#ffffff\" text=\"#000000\">\r\n");
      out.write("\r\n");
      out.write("<form name=\"detailForm\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"37\" border=\"0\" cellpadding=\"0\"\tcellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"15\" height=\"37\"><img src=\"/images/ct_ttl_img01.gif\"\twidth=\"15\" height=\"37\"></td>\r\n");
      out.write("\t\t<td background=\"/images/ct_ttl_img02.gif\" width=\"100%\" style=\"padding-left: 10px;\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"93%\" class=\"ct_ttl01\">상품상세조회</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"20%\" align=\"right\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td width=\"12\" height=\"37\">\r\n");
      out.write("\t\t\t<img src=\"/images/ct_ttl_img03.gif\"  width=\"12\" height=\"37\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\tstyle=\"margin-top: 13px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("\t\t\t상품번호 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"105\">");
      out.print( product.getProdNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("\t\t\t상품명 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print( product.getProdName() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("\t\t\t상품이미지 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">\r\n");
      out.write("\t\t\t<img src = \"/images/uploadFiles/");
      out.print( product.getFileName() );
      out.write("\" onerror=\"this.src='/images/no_image.jpg'\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("\t\t\t상품상세정보 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print( product.getProdDetail() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">제조일자</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print( product.getManuDate() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">가격</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print( product.getPrice() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">등록일자</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print( product.getRegDate() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\tstyle=\"margin-top: 10px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"53%\"></td>\r\n");
      out.write("\t\t<td align=\"right\">\r\n");
      out.write("\r\n");
      out.write("\t\t<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 if("ok".equals(menu)) { 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<td width=\"17\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\" style=\"padding-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/listProduct.do?menu=manage\">확인</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
 if(user != null) { 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td width=\"17\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\" style=\"padding-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/addPurchaseView.do?prodNo=");
      out.print( product.getProdNo() );
      out.write("\">구매</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"30\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<td width=\"17\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\" style=\"padding-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:history.go(-1)\">이전</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
