/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2017-11-02 06:34:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model2.mvc.service.domain.User;
import com.model2.mvc.common.util.CommonUtil;
import com.model2.mvc.common.Page;
import com.model2.mvc.service.domain.Product;
import java.util.List;
import com.model2.mvc.common.Search;

public final class listProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

	List<Product> list = (List<Product>)request.getAttribute("list");
	Page resultPage = (Page)request.getAttribute("resultPage");
	Search search = (Search)request.getAttribute("search");
	User user = (User)session.getAttribute("user");
	
	String menu = (String)request.getAttribute("menu");

	/*
	if("search".equals(menu)) {
		out.println("User 리스트: "+ menu);
	} else {
		out.println("Manage 리스트: "+ menu);
	}
	*/
	
	//==> null 을 ""(nullString)으로 변경
	String searchCondition = CommonUtil.null2str(search.getSearchCondition());
	String searchKeyword = CommonUtil.null2str(search.getSearchKeyword());


      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>상품 목록 조회</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/admin.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("// 검색 / page 두가지 경우 모두 Form 전송을 위해 JavaScrpt 이용  \r\n");
      out.write("function fncGetProductList(currentPage) {\r\n");
      out.write("\tdocument.getElementById(\"currentPage\").value = currentPage;\r\n");
      out.write("   \tdocument.detailForm.submit();\t\t\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#ffffff\" text=\"#000000\">\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:98%; margin-left:10px;\">\r\n");
      out.write("\r\n");
      out.write("<form name=\"detailForm\" action=\"/listProduct.do?menu=");
      out.print(menu);
      out.write("\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"37\" border=\"0\" cellpadding=\"0\"\tcellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"15\" height=\"37\">\r\n");
      out.write("\t\t\t<img src=\"/images/ct_ttl_img01.gif\" width=\"15\" height=\"37\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td background=\"/images/ct_ttl_img02.gif\" width=\"100%\" style=\"padding-left:10px;\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"93%\" class=\"ct_ttl01\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
 if("search".equals(menu)) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t상품 목록조회\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t상품 관리\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td width=\"12\" height=\"37\">\r\n");
      out.write("\t\t\t<img src=\"/images/ct_ttl_img03.gif\" width=\"12\" height=\"37\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-top:10px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t<select name=\"searchCondition\" class=\"ct_input_g\" style=\"width:80px\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"");
      out.print( (searchCondition.equals("0") ? "selected" : ""));
      out.write(">상품번호</option>\r\n");
      out.write("\t\t\t\t<option value=\"1\"");
      out.print( (searchCondition.equals("1") ? "selected" : ""));
      out.write(">상품명</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\"");
      out.print( (searchCondition.equals("2") ? "selected" : ""));
      out.write(">상품가격</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"searchKeyword\" value=\"");
      out.print( searchKeyword );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t class=\"ct_input_g\" style=\"width:200px; height:19px\" />\r\n");
      out.write("\t\t</td>\t\t\r\n");
      out.write("\t\t<td align=\"right\" width=\"70\">\r\n");
      out.write("\t\t\t<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"17\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\" style=\"padding-top:3px;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:fncGetProductList('1');\">검색</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-top:10px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"11\" >\r\n");
      out.write("\t\t전체 ");
      out.print( resultPage.getTotalCount() );
      out.write(" 건수, 현재 ");
      out.print( resultPage.getCurrentPage() );
      out.write(" 페이지</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"ct_list_b\" width=\"100\">No</td>\r\n");
      out.write("\t\t<td class=\"ct_line02\"></td>\r\n");
      out.write("\t\t<td class=\"ct_list_b\" width=\"150\">상품명</td>\r\n");
      out.write("\t\t<td class=\"ct_line02\"></td>\r\n");
      out.write("\t\t<td class=\"ct_list_b\" width=\"150\">가격</td>\r\n");
      out.write("\t\t<td class=\"ct_line02\"></td>\r\n");
      out.write("\t\t<td class=\"ct_list_b\">등록일</td>\t\r\n");
      out.write("\t\t<td class=\"ct_line02\"></td>\r\n");
      out.write("\t\t<td class=\"ct_list_b\">현재상태</td>\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"11\" bgcolor=\"808285\" height=\"1\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

		for (Product vo : list) {
	
      out.write("\r\n");
      out.write("\t<tr class=\"ct_list_pop\">\r\n");
      out.write("\t\t<td align=\"center\">");
      out.print( list.indexOf(vo) + 1 );
      out.write("</td>\r\n");
      out.write("\t\t<td></td>\r\n");
      out.write("\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t");
 if((vo.getProTranCode() == null) || ((user != null) && "admin".equals(user.getRole())) ) { 
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/getProduct.do?prodNo=");
      out.print(vo.getProdNo());
      out.write("&menu=");
      out.print(menu);
      out.write('"');
      out.write('>');
      out.print( vo.getProdName() );
      out.write("</a>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.print( vo.getProdName() );
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td></td>\r\n");
      out.write("\t\t<td align=\"left\">");
      out.print( vo.getPrice() );
      out.write("</td>\r\n");
      out.write("\t\t<td></td>\r\n");
      out.write("\t\t<td align=\"left\">");
      out.print( vo.getRegDate() );
      out.write("</td>\r\n");
      out.write("\t\t<td></td>\r\n");
      out.write("\t\t<td align=\"left\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
 // manager list
		if(vo.getProTranCode()!= null) {
			if(((user != null) && "admin".equals(user.getRole()))) {
				if("1".equals(vo.getProTranCode().trim())) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t구매완료\r\n");
      out.write("\t\t\t");
 	} else if ("2".equals(vo.getProTranCode().trim())) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t배송중\r\n");
      out.write("\t\t\t");
	} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t배송완료\r\n");
      out.write("\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 if(("1".equals(vo.getProTranCode().trim())) && ("manage".equals(menu))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"/updateTranCodeByProd.do?prodNo=");
      out.print(vo.getProdNo());
      out.write("&tranCode=2\">배송하기</a>\r\n");
      out.write("\t\t\t");
 }
		   } else { 
      out.write("\r\n");
      out.write("\t\t\t재고 없음\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
 } } else { 
      out.write("\r\n");
      out.write("\t\t\t판매중\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</td>\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"11\" bgcolor=\"D6D7D6\" height=\"1\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

		}
	
      out.write("\t\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-top:10px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"currentPage\" name=\"currentPage\" value=\"\"/>\r\n");
      out.write("\t\t\t");
 if( resultPage.getCurrentPage() <= resultPage.getPageUnit() ){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:fncGetProductList('");
      out.print(resultPage.getCurrentPage()-1);
      out.write("')\">◀ 이전</a>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
	for(int i=resultPage.getBeginUnitPage();i<= resultPage.getEndUnitPage() ;i++){	
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:fncGetProductList('");
      out.print(i );
      out.write("');\">");
      out.print(i );
      out.write("</a>\r\n");
      out.write("\t\t\t");
 	}  
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t");
 if( resultPage.getEndUnitPage() >= resultPage.getMaxPage() ){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:fncGetProductList('");
      out.print(resultPage.getEndUnitPage()+1);
      out.write("')\">이후 ▶</a>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("    \t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<!--  페이지 Navigator 끝 -->\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
