/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2017-10-31 07:46:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.purchase;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model2.mvc.service.user.vo.UserVO;
import com.model2.mvc.service.product.vo.ProductVO;

public final class addPurchaseView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
 
	ProductVO productVO = (ProductVO)request.getAttribute("productVO");
	UserVO user = (UserVO)session.getAttribute("user");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/admin.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<title>구매하기</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../javascript/calendar.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("function fncAddPurchase() {\r\n");
      out.write("\tdocument.addPurchase.submit();\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form name=\"addPurchase\" method=\"post\" action=\"/addPurchase.do\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"37\" border=\"0\" cellpadding=\"0\"\tcellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"15\" height=\"37\">\r\n");
      out.write("\t\t\t<img src=\"/images/ct_ttl_img01.gif\" width=\"15\" height=\"37\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td background=\"/images/ct_ttl_img02.gif\" width=\"100%\" style=\"padding-left: 10px;\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"93%\" class=\"ct_ttl01\">상품상세조회</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"20%\" align=\"right\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td width=\"12\" height=\"37\">\r\n");
      out.write("\t\t\t<img src=\"/images/ct_ttl_img03.gif\" width=\"12\" height=\"37\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"prodNo\" value=\"");
      out.print( productVO.getProdNo() );
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("<table width=\"600\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\talign=\"center\" style=\"margin-top: 13px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"300\" class=\"ct_write\">\r\n");
      out.write("\t\t\t상품번호 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\" width=\"299\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"105\">");
      out.print( productVO.getProdNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("\t\t\t상품명 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print( productVO.getProdName() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("\t\t\t상품상세정보 <img\tsrc=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print( productVO.getProdDetail() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">제조일자</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print( productVO.getManuDate() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">가격</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print( productVO.getPrice() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">등록일자</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print( productVO.getRegDate() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("\t\t\t구매자아이디 <img \tsrc=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">");
      out.print( user.getUserId() );
      out.write("</td>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"buyerId\" value=\"");
      out.print( user.getUserId());
      out.write("\" />\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">구매방법</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">\r\n");
      out.write("\t\t\t<select name=\"paymentOption\" class=\"ct_input_g\" \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100px; height: 19px\" maxLength=\"20\">\r\n");
      out.write("\t\t\t\t<option value=\"1\" selected=\"selected\">현금구매</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">신용구매</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">구매자이름</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"receiverName\" \tclass=\"ct_input_g\" \r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 100px; height: 19px\" maxLength=\"20\" value=\"");
      out.print( user.getUserName() );
      out.write("\" />\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">구매자연락처</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">\r\n");
      out.write("\t\t\t<input \ttype=\"text\" name=\"receiverPhone\" class=\"ct_input_g\" \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100px; height: 19px\" maxLength=\"20\" value=\"");
      out.print( user.getPhone() );
      out.write("\" />\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">구매자주소</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">\r\n");
      out.write("\t\t\t<input \ttype=\"text\" name=\"receiverAddr\" class=\"ct_input_g\" \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100px; height: 19px\" maxLength=\"20\" \tvalue=\"");
      out.print( user.getAddr() );
      out.write("\" />\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">구매요청사항</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td class=\"ct_write01\">\r\n");
      out.write("\t\t\t<input\t\ttype=\"text\" name=\"receiverRequest\" \tclass=\"ct_input_g\" \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100px; height: 19px\" maxLength=\"20\" />\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"104\" class=\"ct_write\">배송희망일자</td>\r\n");
      out.write("\t\t<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("\t\t<td width=\"200\" class=\"ct_write01\">\r\n");
      out.write("\t\t\t<input \ttype=\"text\" readonly=\"readonly\" name=\"receiverDate\" class=\"ct_input_g\" \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100px; height: 19px\" maxLength=\"20\"/>\r\n");
      out.write("\t\t\t<img \tsrc=\"../images/ct_icon_date.gif\" width=\"15\" height=\"15\"\t\r\n");
      out.write("\t\t\t\t\t\tonclick=\"show_calendar('document.addPurchase.receiverDate', document.addPurchase.receiverDate.value)\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-top: 10px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"53%\"></td>\r\n");
      out.write("\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"17\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\" style=\"padding-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:fncAddPurchase();\">구매</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"30\"></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"17\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\" style=\"padding-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:history.go(-1)\">취소</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"14\" height=\"23\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
