/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2017-10-31 11:33:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.purchase;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model2.mvc.service.purchase.vo.PurchaseVO;
import java.util.ArrayList;
import com.model2.mvc.common.SearchVO;
import java.util.HashMap;

public final class listPurchase_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

	HashMap<String, Object> map = (HashMap<String, Object>) request.getAttribute("map");
	SearchVO searchVO = (SearchVO)request.getAttribute("searchVO");
	
	int total = 0;
	ArrayList<PurchaseVO> list = null;
	if(map != null) {
		total = ((Integer)map.get("count")).intValue();
		list = (ArrayList<PurchaseVO>)map.get("list");
	}
	
	int currentPage = searchVO.getPage();
	
	int totalPage = 0;
	if(total > 0) {
		totalPage = total / searchVO.getPageUnit();
		if (total%searchVO.getPageUnit() > 0) {
			totalPage += 1;
		}
	}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>구매 목록조회</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/admin.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("\tfunction fncGetUserList() {\r\n");
      out.write("\t\tdocument.detailForm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#ffffff\" text=\"#000000\">\r\n");
      out.write("\r\n");
      out.write("<div style=\"width: 98%; margin-left: 10px;\">\r\n");
      out.write("\r\n");
      out.write("<form name=\"detailForm\" action=\"/listUser.do\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"37\" border=\"0\" cellpadding=\"0\"\tcellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"15\" height=\"37\"><img src=\"/images/ct_ttl_img01.gif\"width=\"15\" height=\"37\"></td>\r\n");
      out.write("\t\t<td background=\"/images/ct_ttl_img02.gif\" width=\"100%\" style=\"padding-left: 10px;\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"93%\" class=\"ct_ttl01\">구매 목록조회</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td width=\"12\" height=\"37\"><img src=\"/images/ct_ttl_img03.gif\"\twidth=\"12\" height=\"37\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\tstyle=\"margin-top: 10px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"11\">전체 ");
      out.print( total );
      out.write(" 건수, 현재 ");
      out.print( currentPage );
      out.write(" 페이지</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"ct_list_b\" width=\"100\">No</td>\r\n");
      out.write("\t\t<td class=\"ct_line02\"></td>\r\n");
      out.write("\t\t<td class=\"ct_list_b\" width=\"150\">회원ID</td>\r\n");
      out.write("\t\t<td class=\"ct_line02\"></td>\r\n");
      out.write("\t\t<td class=\"ct_list_b\" width=\"150\">회원명</td>\r\n");
      out.write("\t\t<td class=\"ct_line02\"></td>\r\n");
      out.write("\t\t<td class=\"ct_list_b\">전화번호</td>\r\n");
      out.write("\t\t<td class=\"ct_line02\"></td>\r\n");
      out.write("\t\t<td class=\"ct_list_b\">배송현황</td>\r\n");
      out.write("\t\t<td class=\"ct_line02\"></td>\r\n");
      out.write("\t\t<td class=\"ct_list_b\">정보수정</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"11\" bgcolor=\"808285\" height=\"1\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

		int no = list.size();
		for (PurchaseVO vo : list) {	
	
      out.write("\t\r\n");
      out.write("\t<tr class=\"ct_list_pop\">\r\n");
      out.write("\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t<a href=\"/getPurchase.do?tranNo=");
      out.print( vo.getTranNo() );
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print( no-- );
      out.write("</a>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td></td>\r\n");
      out.write("\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t<a href=\"/getUser.do?userId=");
      out.print( vo.getBuyer().getUserId() );
      out.write("\">\r\n");
      out.write("\t\t\t");
      out.print( vo.getBuyer().getUserId() );
      out.write("</a>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td></td>\r\n");
      out.write("\t\t<td align=\"left\">");
      out.print( vo.getReceiverName() );
      out.write("</td>\r\n");
      out.write("\t\t<td></td>\r\n");
      out.write("\t\t<td align=\"left\">");
      out.print( vo.getReceiverPhone() );
      out.write("</td>\r\n");
      out.write("\t\t<td></td>\r\n");
      out.write("\t\t<td align=\"left\">\r\n");
      out.write("\t\t현재\r\n");
      out.write("\t\t");

			if("1".equals(vo.getTranCode().trim())) {
		
      out.write("\r\n");
      out.write("\t\t\t구매완료\r\n");
      out.write("\t\t");
 
			} else if("2".equals(vo.getTranCode().trim())) { 
		
      out.write("\r\n");
      out.write("\t\t\t배송중\r\n");
      out.write("\t\t");

			} else {
		
      out.write("\r\n");
      out.write("\t\t\t배송완료\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t상태입니다.\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td></td>\r\n");
      out.write("\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"11\" bgcolor=\"D6D7D6\" height=\"1\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-top: 10px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\">\r\n");
      out.write("\t\t ");

		 	for(int i=1; i<=totalPage; i++) {
		 
      out.write("\r\n");
      out.write("\t\t\t<a href=\"/listPurchase.do?page=");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</a> \r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<!--  페이지 Navigator 끝 -->\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
