/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2017-12-07 06:44:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  ///////////////////////// JSTL  ////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ///////////////////////////// 로그인시 Forward  /////////////////////////////////////// -->\r\n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" <!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\t\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"EUC-KR\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 참조 : http://getbootstrap.com/css/   -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!--  ///////////////////////// Bootstrap, jQuery CDN ////////////////////////// -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" >\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" ></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--  ///////////////////////// CSS ////////////////////////// -->\r\n");
      out.write("\t<style></style>\r\n");
      out.write("   \t\r\n");
      out.write("   \t<!--  ///////////////////////// JavaScript ////////////////////////// -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//============= 회원원가입 화면이동 =============\r\n");
      out.write("\t\t$( function() {\r\n");
      out.write("\t\t\t//==> 추가된부분 : \"addUser\"  Event 연결\r\n");
      out.write("\t\t\t$(\"a[href='#' ]:contains('회원가입')\").on(\"click\" , function() {\r\n");
      out.write("\t\t\t\tself.location = \"/user/addUser\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//============= 로그인 화면이동 =============\r\n");
      out.write("\t\t$( function() {\r\n");
      out.write("\t\t\t//==> 추가된부분 : \"addUser\"  Event 연결\r\n");
      out.write("\t\t\t$(\"a[href='#' ]:contains('로 그 인')\").on(\"click\" , function() {\r\n");
      out.write("\t\t\t\tself.location = \"/user/login\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$( function() {\r\n");
      out.write("\t\t\t//==> 추가된부분 : \"addUser\"  Event 연결\r\n");
      out.write("\t\t\t$(\"a[href='#' ]:contains('상품검색')\").on(\"click\" , function() {\r\n");
      out.write("\t\t\t\t$(self.location).attr(\"href\",\"/product/listProduct?menu=search\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ToolBar Start /////////////////////////////////////-->\r\n");
      out.write("\t<div class=\"navbar  navbar-default\">\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("        \r\n");
      out.write("        \t<a class=\"navbar-brand\" href=\"#\">Model2 MVC Shop</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- toolBar Button Start //////////////////////// -->\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t    <button class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#target\">\r\n");
      out.write("\t\t\t        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t        <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t        <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t        <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t    </button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- toolBar Button End //////////////////////// -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"  id=\"target\">\r\n");
      out.write("\t             <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t                 <li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("\t                 <li><a href=\"#\">로 그 인</a></li>\r\n");
      out.write("\t           \t</ul>\r\n");
      out.write("\t       </div>\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t</div>\r\n");
      out.write("   \t<!-- ToolBar End /////////////////////////////////////-->\r\n");
      out.write("   \t\r\n");
      out.write("\t<!--  화면구성 div Start /////////////////////////////////////-->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 다단레이아웃  Start /////////////////////////////////////-->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<!--  Menu 구성 Start /////////////////////////////////////-->     \t\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t       \t<!--  회원관리 목록에 제목 -->\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"glyphicon glyphicon-heart\"></i> 회원관리\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("         \t\t\t<!--  회원관리 아이템 -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t <li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t \t<a href=\"#\">개인정보조회</a> <i class=\"glyphicon glyphicon-ban-circle\"></i>\r\n");
      out.write("\t\t\t\t\t\t </li>\r\n");
      out.write("\t\t\t\t\t\t <li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t \t<a href=\"#\">회원정보조회</a> <i class=\"glyphicon glyphicon-ban-circle\"></i>\r\n");
      out.write("\t\t\t\t\t\t </li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-briefcase\"></i> 판매상품관리\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t <li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t \t<a href=\"#\">판매상품등록</a> <i class=\"glyphicon glyphicon-ban-circle\"></i>\r\n");
      out.write("\t\t\t\t\t\t </li>\r\n");
      out.write("\t\t\t\t\t\t <li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t \t<a href=\"#\">판매상품관리</a> <i class=\"glyphicon glyphicon-ban-circle\"></i>\r\n");
      out.write("\t\t\t\t\t\t </li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-shopping-cart\"></i> 상품구매\r\n");
      out.write("\t    \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t <li class=\"list-group-item\"><a href=\"#\">상품검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t  <li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t  \t<a href=\"#\">구매이력조회</a> <i class=\"glyphicon glyphicon-ban-circle\"></i>\r\n");
      out.write("\t\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t\t <li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t \t<a href=\"#\">최근본상품</a> <i class=\"glyphicon glyphicon-ban-circle\"></i>\r\n");
      out.write("\t\t\t\t\t\t </li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--  Menu 구성 end /////////////////////////////////////-->   \r\n");
      out.write("\r\n");
      out.write("\t \t \t<!--  Main start /////////////////////////////////////-->   \t\t\r\n");
      out.write("\t \t \t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t<div class=\"jumbotron\">\r\n");
      out.write("\t\t\t  \t\t<h1>Model2 MVC Shop</h1>\r\n");
      out.write("\t\t\t  \t\t<p>로그인 후 사용가능...</p>\r\n");
      out.write("\t\t\t  \t\t<p>로그인 전 검색만 가능합니다.</p>\r\n");
      out.write("\t\t\t  \t\t<p>회원가입 하세요.</p>\r\n");
      out.write("\t\t\t  \t\t\r\n");
      out.write("\t\t\t  \t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t  \t\t\t<a class=\"btn btn-info btn-lg\" href=\"#\" role=\"button\">회원가입</a>\r\n");
      out.write("\t\t\t  \t\t\t<a class=\"btn btn-info btn-lg\" href=\"#\" role=\"button\">로 그 인</a>\r\n");
      out.write("\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t  \t\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t   \t \t<!--  Main end /////////////////////////////////////-->   \t\t\r\n");
      out.write("\t \t \t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 다단레이아웃  end /////////////////////////////////////-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--  화면구성 div end /////////////////////////////////////-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /index.jsp(9,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ ! empty user }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write(" \t");
        if (true) {
          _jspx_page_context.forward("main.jsp");
          return true;
        }
        out.write('\r');
        out.write('\n');
        out.write(' ');
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
